# Generated by Django 3.1 on 2020-09-15 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_productreview_review_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.order'),
            preserve_default=False,
        ),
    ]
