# Generated by Django 3.1 on 2020-09-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20200906_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_verified',
            field=models.BooleanField(default=False),
        ),
    ]
